ci(circleci): add codacy file to test report
voiceflow/runtime pull request #84
Opened 2021-01-20 10:45 UTC by xavidop

2021-01-26 17:36 UTC, frankgu968 requested changes

2021-01-26 17:36 UTC, frankgu968 commented on .codacy.yml
> +---
Let's clean up the legacy Codacy files

2021-01-26 18:21 UTC, xavidop commented on .codacy.yml
> +---
removed

2021-01-26 18:39 UTC, merged

2021-01-29 15:57 UTC, voiceflow-dev commented
:tada: This PR is included in version 1.21.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/runtime/v/1.21.0)
- [GitHub release](https://github.com/voiceflow/runtime/releases/tag/v1.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: