feat: common to ts
voiceflow/runtime pull request #91
Opened 2021-01-28 18:59 UTC by z4o4z

**Fixes or implements CORE-XXX**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] title of PR reflects the branch name
- [ ] all commits adhere to conventional commits
- [ ] appropriate tests have been written
- [ ] all the dependendencies are upgraded

2021-01-28 20:25 UTC, leartgjoni-voiceflow requested changes

2021-01-28 20:25 UTC, leartgjoni-voiceflow commented on README.md
> +  _ the runtime handles state management and tracks the user's state at each turn of conversation
`*` -> `_` is this an automatic linting thing?

2021-01-29 15:41 UTC, DecathectZero approved these changes

2021-01-29 15:49 UTC, leartgjoni-voiceflow approved these changes

2021-01-29 15:53 UTC, merged

2021-01-29 15:57 UTC, voiceflow-dev commented
:tada: This PR is included in version 1.21.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/runtime/v/1.21.0)
- [GitHub release](https://github.com/voiceflow/runtime/releases/tag/v1.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: